# 1)შემოატენინეთ მომხმარებელს ორი რიცხვი და შეადარეთ ისინი ერთმანეთს
number = int(input("enter your number: "))
print(number)
number2 = int(input("enter your number2: "))
print(number2)
print(number==number2)
print(number!=number2)
print(number<number2)
print(number>number2)
print(number%number2)