# 3)მომხმარებელს შემოატანინეთ ორი რიცხვი და მათზე მოახდინეთ მათემატიკური ოპერაციები.(მიმატება,გამოკლება,გამრავლება,გაყოფა)
number = int(input("enter your number: "))
print(number)
number2 = int(input("enter your number2: "))
print(number2)
print(number+number2)
print(number-number2)
print(number*number2)
print(number/number2)
